# Configuration file
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.log.sql=false
quarkus.application.name=myservice
quarkus.minecrafter.devservices.port=25565
#quarkus.minecrafter.animal-type=pig
#quarkus.minecrafter.model.base-url=http://localhost:11434/v1/
#quarkus.minecrafter.model.base-url=https://api.openai.com/v1/
#quarkus.minecrafter.model.api-key=${OPENAI_KEY}
#quarkus.minecrafter.model.name=o4-mini
