#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
git apply $SCRIPT_DIR/demo-prep.patch

(cd $SCRIPT_DIR/../modded-minecraft/ && ./gradlew runClient & )

idea $SCRIPT_DIR/..
